### ISSUE TITLE
Errors running builder 'Checkstyle Builder' on project 'carisma.check.smartcard.evolution'

### ISSUE THREAD

**Issue by APHDKO** [CARiSMA-Tool/carisma-tool#16]
Errors occurred during the build.
Errors running builder 'Checkstyle Builder' on project 'carisma.check.smartcard.evolution'.
Fileset from project "carisma.check.smartcard.evolution" has no valid check configuration.
Fileset from project "carisma.check.smartcard.evolution" has no valid check configuration.
Fileset from project "carisma.check.smartcard.evolution" has no valid check configuration.
Fileset from project "carisma.check.smartcard.evolution" has no valid check configuration.

**Comment by nuthub** [comment]
checkstylebuider removed
