### ISSUE TITLE
Missing dependency in carisma.check.createHelpDocument

### ISSUE THREAD

**Issue by seiferma** [CARiSMA-Tool/carisma-tool#3]
The project `carisma.check.createHelpDocument` depends on a bundle called `carisma.ui.vision`, which is not available from the repository. This also produces an issue when trying to install some features from the update site.

**Comment by SvenPeldszus** [comment]
This plugin is contained in the VisiOn Feature in the "CARiSMA Project Specific Features" category of the update site.

The source code is contained in the vision branch of CARiSMA.

However, the main branch shouldn't have a dependency on this. I'll remove the dependency as soon as possible. Until then, installing the dependency from the update site should fix the issue.

**Comment by nuthub** [comment]
fixed by 8377b9d599c638045f41dce45c9b680640620aab
