### ISSUE TITLE
Configure JaCoCo in maven projects to measure test coverage

### ISSUE THREAD

**Issue by nuthub** [CARiSMA-Tool/carisma-tool#32]
Currently, JaCoCo reports 0% to Sonarcloud: https://github.com/CARiSMA-Tool/carisma-tool/runs/17328597613

**Comment by APHDKO** [comment]
Reconsider plugins to measure.

**Comment by APHDKO** [comment]
Investigate difference of coverage in local report and sonarcloud report.
E.g. : `plugins/carisma.ui.eclipse` ignored in local report while considered in sonarcloud report

**Comment by APHDKO** [comment]
Difference in measurement of local coverage and coverage on sonar
