### ISSUE TITLE
CARiSMA perspective broken

### ISSUE THREAD

**Issue by nuthub** [CARiSMA-Tool/carisma-tool#41]
workspace's perspective does not switch, when user selects CARiSMA Perspective.

This happens via

1. CARiSMA -> CARiSMA perspective
2. Window -> Perspective -> Open Perspective -> Other -> CARiSMA

**Comment by nuthub** [comment]
Add ModelExplorer View to perspective

**Comment by APHDKO** [comment]
Persprective works , Model Explorer is still missing
<img width="1919" alt="CARiSMA_Perspective_desired" src="https://github.com/CARiSMA-Tool/carisma-tool/assets/61877601/9702aecb-67e7-4d42-8897-70e89c714b4d">

**Comment by APHDKO** [comment]
Closed with 8ca0313
