### ISSUE TITLE
Issues when trying to run the secure dependency example check

### ISSUE THREAD

**Issue by LaIsaTr** [CARiSMA-Tool/carisma-tool#9]
Hello :)

I have tried running the secure dependency check example described [here](https://rgse.uni-koblenz.de/carisma/securedependency.shtml) but I'm facing issues getting it to work. 

I have downloaded the uml file example and imported it into an empty project in Eclipse.
Then I created a CARiSMA analysis and added the secure dependency check to it. When I hit RUN all checks appear to be "successful" but when I create the report of the analysis I get following output.

```
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
Running check : UMLsec secure dependency Check
------------------------------------------------------------------------------------

Processing dependency 'InterfaceRealization1' between 'null' and 'null'
- not in scope of <<secure dependency>> -> nothing to check!

Processing dependency 'null' between 'null' and 'null'
- not in scope of <<secure dependency>> -> nothing to check!

------------------------------------------------------------------------------------
The analysis detected 0 errors.
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
```

So far I have tried different Eclipse versions and I have also tried to replicate the example from scratch with Papyrus and UmlSec stereotypes but unfortunately that did not produce any successful results either.

Any ideas why this is failing? 

Any help would be greatly appreciated. Thank you,
Laura

---

Additional details:
- Windows 11
- Eclipse Modeling Tools: 2022-03; also tried 2021-06, 2019-06, Photon and Oxygen
- installed CARiSMA via Update Site

**Comment by SvenPeldszus** [comment]
Dear Laura,

this sounds like the <<secure dependency>> stereotype, which specifies that the contained elements are in the scope of secure dependency, is missing on the `Model` or `Package` containing the classes. Can you please check if this is the case?

Best Sven

**Comment by LaIsaTr** [comment]
Hello Sven,

Thanks for your reply. I have imported the example uml file that you provide [here](https://rgse.uni-koblenz.de/carisma/securedependency.shtml) and I believe it does have the required <<secure dependency>> stereotype you mentioned. 

Best, 
Laura

**Comment by nuthub** [comment]
Dear Laura,

could you please try the example that can be found here https://github.com/CARiSMA-Tool/carisma-tool/tree/examples/examples/secure-dependency ?

Best Regards,
Julian

**Comment by APHDKO** [comment]
Bug fixed, you can try the new [examples](https://github.com/CARiSMA-Tool/carisma-tool/tree/master/examples/static-check-examples/secure-dependecy-examples) here.
